### ISSUE TITLE
report problems

### ISSUE THREAD

**Issue by ahfuzhang** [dolthub/swiss#24]
1. see: https://github.com/dolthub/swiss/blob/c0064a04cd348d5e57676225b6d34a27c56c6700/bits_amd64.go#L34
    The group size is 8, but when use simd, it convert to 16.
    If the locate is the last one, programe might be coredump, or result not correct.

2. compare with https://github.com/rust-lang/hashbrown, group size should be 16.

3. group count should be one more.
    when the locate is ths last one, and use unalign load, the last one more group can avoid out of range.

Sorry, I think this library still has a lot of bugs and is far from reaching a level that can be actually used.

**Comment by reltuk** [comment]
1) As far as I know, for `amd64` with `simd`, `groupSize` is `16`. See https://github.com/dolthub/swiss/blob/c0064a04cd348d5e57676225b6d34a27c56c6700/bits_amd64.go#L27 .

2) For number 3, is the claim that `numGroups` computes a slice that is too small? Can you provide an example of input that performs a load off the end of the allocated slice?

Thanks for your interest in the project and your report :).

**Comment by ahfuzhang** [comment]
Thank you so much, I will test it again.
