### ISSUE TITLE
Incorrect result?

### ISSUE THREAD

**Issue by kokizzu** [dolthub/swiss#3]
Hi, I was trying to reproduce map benchmark using swiss
https://github.com/kokizzu/kokizzu-benchmark/blob/master/assoc/go-swiss/swiss.go
https://github.com/kokizzu/kokizzu-benchmark/blob/master/assoc/map.go

https://pastebin.com/diff/SBZXSPFb
but I got different result when using swiss
```shell
time go run map.go
6009354 6009348 611297
36186112 159701682 23370001

CPU: 14.36s     Real: 12.60s    RAM: 2269936KB

time go run go-swiss/swiss.go  
6009354 6009348 611297
1 6 1 --> should be the same as above

CPU: 13.06s     Real: 12.14s    RAM: 1837384KB
```

**Comment by kokizzu** [comment]
my bad, should be return false on iter

**Comment by andy-wm-arthur** [comment]
Hey @kokizzu, thanks for trying out SwissMap! Let me know if you have any other questions or concerns 😄
