### ISSUE TITLE
Broken link in the ReadMe

### ISSUE THREAD

**Issue by LuisLSousa** [dolthub/swiss#4]
This is evidently a very small issue, but the ["Go Playground" hyperlink](https://github.com/dolthub/swiss/#:~:text=try%20using%20this-,Go%20playground.,-package%20main%0A%0Aimport) in the readme redirects to https://github.com/dolthub/swiss/blob/main, which is a 404 page.

![image](https://user-images.githubusercontent.com/48560651/229173544-4b67ba13-1710-4a9e-9626-d6df3312c2d4.png)

**Comment by andy-wm-arthur** [comment]
Thanks for the tip @LuisLSousa! ~~I'll fix it~~ Should be fixed now.
