### ISSUE TITLE
Is swiss concurrency safe?

### ISSUE THREAD

**Issue by lufishggg** [dolthub/swiss#9]

**Comment by andy-wm-arthur** [comment]
Hey @lufishggg!

SwissMap is _not_ thread safe. However, I have been noodling on a concurrent version. I'll post an update here if anything changes

**Comment by mhmtszr** [comment]
Hi @lufishggg, you may want to try https://github.com/mhmtszr/concurrent-swiss-map

**Comment by reltuk** [comment]
Closing this as answered.
